### YamlMime:ManagedReference
items:
- uid: TcOpen.Inxton.Security
  commentId: N:TcOpen.Inxton.Security
  id: TcOpen.Inxton.Security
  children:
  - TcOpen.Inxton.Security.AuthenticationServiceNotActiveException
  - TcOpen.Inxton.Security.AuthorizationRequestDelegate
  - TcOpen.Inxton.Security.AuthorizationTokenChangeRequestDelegate
  - TcOpen.Inxton.Security.IAuthenticationService
  - TcOpen.Inxton.Security.IExternalAuthorization
  - TcOpen.Inxton.Security.ISecurityManager
  - TcOpen.Inxton.Security.ISecurityManagerUserInfo
  - TcOpen.Inxton.Security.ISecurityProvider
  - TcOpen.Inxton.Security.IUser
  - TcOpen.Inxton.Security.OnTimedLogoutRequestDelegate
  - TcOpen.Inxton.Security.OnUserAuthentication
  - TcOpen.Inxton.Security.Role
  langs:
  - csharp
  - vb
  name: TcOpen.Inxton.Security
  nameWithType: TcOpen.Inxton.Security
  fullName: TcOpen.Inxton.Security
  type: Namespace
  assemblies:
  - TcOpen.Inxton.Abstractions
references:
- uid: TcOpen.Inxton.Security.AuthenticationServiceNotActiveException
  commentId: T:TcOpen.Inxton.Security.AuthenticationServiceNotActiveException
  name: AuthenticationServiceNotActiveException
  nameWithType: AuthenticationServiceNotActiveException
  fullName: TcOpen.Inxton.Security.AuthenticationServiceNotActiveException
- uid: TcOpen.Inxton.Security.IAuthenticationService
  commentId: T:TcOpen.Inxton.Security.IAuthenticationService
  parent: TcOpen.Inxton.Security
  name: IAuthenticationService
  nameWithType: IAuthenticationService
  fullName: TcOpen.Inxton.Security.IAuthenticationService
- uid: TcOpen.Inxton.Security.IExternalAuthorization
  commentId: T:TcOpen.Inxton.Security.IExternalAuthorization
  parent: TcOpen.Inxton.Security
  name: IExternalAuthorization
  nameWithType: IExternalAuthorization
  fullName: TcOpen.Inxton.Security.IExternalAuthorization
- uid: TcOpen.Inxton.Security.AuthorizationRequestDelegate
  commentId: T:TcOpen.Inxton.Security.AuthorizationRequestDelegate
  parent: TcOpen.Inxton.Security
  name: AuthorizationRequestDelegate
  nameWithType: AuthorizationRequestDelegate
  fullName: TcOpen.Inxton.Security.AuthorizationRequestDelegate
- uid: TcOpen.Inxton.Security.AuthorizationTokenChangeRequestDelegate
  commentId: T:TcOpen.Inxton.Security.AuthorizationTokenChangeRequestDelegate
  parent: TcOpen.Inxton.Security
  name: AuthorizationTokenChangeRequestDelegate
  nameWithType: AuthorizationTokenChangeRequestDelegate
  fullName: TcOpen.Inxton.Security.AuthorizationTokenChangeRequestDelegate
- uid: TcOpen.Inxton.Security.ISecurityManager
  commentId: T:TcOpen.Inxton.Security.ISecurityManager
  name: ISecurityManager
  nameWithType: ISecurityManager
  fullName: TcOpen.Inxton.Security.ISecurityManager
- uid: TcOpen.Inxton.Security.ISecurityManagerUserInfo
  commentId: T:TcOpen.Inxton.Security.ISecurityManagerUserInfo
  name: ISecurityManagerUserInfo
  nameWithType: ISecurityManagerUserInfo
  fullName: TcOpen.Inxton.Security.ISecurityManagerUserInfo
- uid: TcOpen.Inxton.Security.ISecurityProvider
  commentId: T:TcOpen.Inxton.Security.ISecurityProvider
  name: ISecurityProvider
  nameWithType: ISecurityProvider
  fullName: TcOpen.Inxton.Security.ISecurityProvider
- uid: TcOpen.Inxton.Security.IUser
  commentId: T:TcOpen.Inxton.Security.IUser
  parent: TcOpen.Inxton.Security
  name: IUser
  nameWithType: IUser
  fullName: TcOpen.Inxton.Security.IUser
- uid: TcOpen.Inxton.Security.OnTimedLogoutRequestDelegate
  commentId: T:TcOpen.Inxton.Security.OnTimedLogoutRequestDelegate
  parent: TcOpen.Inxton.Security
  name: OnTimedLogoutRequestDelegate
  nameWithType: OnTimedLogoutRequestDelegate
  fullName: TcOpen.Inxton.Security.OnTimedLogoutRequestDelegate
- uid: TcOpen.Inxton.Security.OnUserAuthentication
  commentId: T:TcOpen.Inxton.Security.OnUserAuthentication
  parent: TcOpen.Inxton.Security
  name: OnUserAuthentication
  nameWithType: OnUserAuthentication
  fullName: TcOpen.Inxton.Security.OnUserAuthentication
- uid: TcOpen.Inxton.Security.Role
  commentId: T:TcOpen.Inxton.Security.Role
  parent: TcOpen.Inxton.Security
  name: Role
  nameWithType: Role
  fullName: TcOpen.Inxton.Security.Role
- uid: TcOpen.Inxton.Security
  commentId: N:TcOpen.Inxton.Security
  name: TcOpen.Inxton.Security
  nameWithType: TcOpen.Inxton.Security
  fullName: TcOpen.Inxton.Security
